name: Deploy to Railway

on:
  push:
    branches:
      - master # Change to your deployment branch if not master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway Workspace
        run: railway up --detach --project-id ${{ secrets.RAILWAY_PROJECT_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
